sudo: required
dist: trusty
language: cpp

os:
  - linux

addons:
  apt:
    packages: ['libprotobuf-dev', 'libgoogle-glog-dev', 'protobuf-compiler']

compiler:
  - gcc

language: cpp

script:
  - make -C third/slash/slash
  - make -C third/pink/pink SLASH_PATH=../../slash
  - make -C libzp/libzp
  - make -C manager
